### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Adam-Ladd** [TylerBloom/CycleMap#5]
Hi is this project abandoned? 

There are a tonne of commits up until about a year ago, then nothing, with a number of issues left open. This leads me to think that this crate is abandoned is this correct?

**Comment by Adam-Ladd** [comment]
The mention of hashbrown in some of the docs (now the standard hashmap in rust) also leads me to suspect this crate is outdated.

**Comment by TylerBloom** [comment]
Hey :wave:, I think we talked on Reddit, but I repeat myself here too. I do need to do a better job at maintaining this crate, and I plan on auditing and revisiting this crate before the end of the year (currently refreshing myself with changes to the hashbrown crate).

As for the mention of hashbrown, hashbrown has been the implementation that `std` has used since I first built this crate; however, the hashbrown crate offers a `RawTable` interface, which is what is used internally. This is how `key <-> key` mapping can happen without needing individual allocations for each item or needing to clone each element.
